// <auto-generated />
namespace SMM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addColumns_MainInfo_AdditinalInfo_JSonCards_IN_Project : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumns_MainInfo_AdditinalInfo_JSonCards_IN_Project));
        
        string IMigrationMetadata.Id
        {
            get { return "201806081959373_addColumns_MainInfo_AdditinalInfo_JSonCards_IN_Project"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
