// <auto-generated />
namespace SMM.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addColumn_OKId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addColumn_OKId));
        
        string IMigrationMetadata.Id
        {
            get { return "201804180951392_addColumn_OKId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
